Теперь добавьте конфигурацию в файл push.yaml:

name: Go
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.23.1
    steps:
      - uses: actions/checkout@v4

      - name: Run Unit Tests
        run: GOOS=linux GOARCH=amd64 go test

      - name: Vet
        run: |
          go vet ./....